title: Asignaturas_IS
description: Contenidosde la asignatura Introducción a la Ingeniería de software
author: Mildred Rodriguez
avatar: /fotoportada.jpeg
email: ngzhio@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: MildredRodriguez1205
  card: summary
logo: fotoportada.jpeg
social:
  name: Mildred Rodriguez
  links:
  https://github.com/MildredRodriguez1205
    
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
